import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins, Sen } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400", "600", "700"],
});
const sen = Sen({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sen",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${sen.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
